version: '2.0'

services:
   apache:
     build:
       context: .
       dockerfile: dockerfile
     ports:
       - 8082:80
     volumes:
       - /test/web:/var/www/html
     restart: always

   db:
     container_name: mysql
     image: mysql:5.7
     volumes:
       - wp_db:/var/lib/mysql/
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: passwordwp
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     networks:
     - wp
     
   wordpress:
     depends_on:
       - db
     container_name: wordpress
     image: wordpress:latest
     volumes:
       - wp_statics:/var/www/html/
     ports:
       - 8000:80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     networks:
     - wp
     
   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     restart: always
     ports:
       - 8081:80
     environment:
       PMA_HOST: db
       MYSQL_ROOT_PASSWORD: password
     networks:
     - wp

networks:
  wp:

volumes:
  wp_db: #sauvegarde de la bdd en local
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/wordpress/db
  wp_statics: #sauvegarde des data wp
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/wordpress/statics
